#!python
"""
Do not use % sign in descriptions.
"""
from backend import app, logging_extra
from typing import List
import argparse
import os
import sys


class rc(object):
    """ Custom arg-parsing object that relies on user commands """
    pass
    def __init__(self):
        funcs = [f'> {f}' for f in dir(self) if callable(getattr(self, f)) and '__' not in f]
        funcs_str = '\n'.join(funcs)
        parser = argparse.ArgumentParser(
            prog='rc',
            usage=f"""
Main tool for repo

Available commands:
{funcs_str}

""",
            epilog="""""",
        )
        parser.add_argument('command', help='command to run')
        # TODO: low: enumerate potential commands for users in help message
        args = parser.parse_args(sys.argv[1:2])
        if not hasattr(self, args.command):
            print(f'Unrecognized command: {args.command}')
            parser.print_help()
            exit(1)
        # use dispatch pattern to invoke method with same name
        getattr(self, args.command)()


    # Commands
    def asr(self):
        default_port = 7861
        parser = argparse.ArgumentParser(
            prog=None,
            usage=f"""
Boot ASR server
Default port: {default_port}
    """,
        )
        parser.add_argument('-p', '--port', required=False, default=default_port, type=int, help='Optional: specify a port to use')
        args = parser.parse_args(sys.argv[2:])
        app.asr(

        )


    def counttokens(self):
        parser = argparse.ArgumentParser(
            usage="""
Description: count tokens of a file for files

Form:
- python nx counttokens -i [file path/dir path] -m [model path]

Examples:
- python nx counttokens -i /projects/MyProject/                                   -m /models/Meta-LLama-3.1/
- python nx counttokens -i /projects/MyProject/init.py                            -m /models/Meta-LLama-3.1/
- python nx counttokens -i /projects/MyProject/init.py /projects/MyProject/app.py -m /models/Meta-LLama-3.1/
""",
        )
        parser.add_argument('-i', '--input', required=True, type=str, nargs='+', help='Required: ')
        parser.add_argument('-m', '--model', required=False, help='Optional: specify model path from which the tokenizer will be used')
        args = parser.parse_args(sys.argv[2:])
        app.counttokens(
            args.input,
            args.model,
        )


    def mp3towav(self):
        parser = argparse.ArgumentParser(
            prog=None,
            usage="""
Description: convert mp3 to wav
Form:
- python nx mp3towav -i [mp3path] -o [wavpath]
Examples:
- python nx mp3towav -i music.mp3 -o music.wav

    """,
        )
        parser.add_argument('-i', '--input', required=True, help='Required: a path to an mp3 file')
        parser.add_argument('-o', '--output', required=True, help='Required: a path to output wav file. ')
        parser.add_argument('-f', '--force', required=False, action='store_true', default=False, help='Optional: force overwrite')
        args = parser.parse_args(sys.argv[2:])
        app.mp3towav(
            args.input,
            args.output,
            force=args.force,
        )

    def mp4tomp3(self):
        parser = argparse.ArgumentParser(
            prog=None,
            usage="""
Description: convert mp4 to mp3
Form:
- python nx mp4tomp3 -i [mp3path] -o [wavpath]
Examples:
- python nx mp4tomp3 -i music.mp3 -o music.wav

    """,
        )
        parser.add_argument('-i', '--input', required=True, help='Required: a path to an mp3 file')
        parser.add_argument('-o', '--output', required=True, help='Required: a path to output wav file')
        parser.add_argument('-f', '--force', required=False, action='store_true', default=False, help='Optional: force overwrite')
        args = parser.parse_args(sys.argv[2:])
        app.mp4tomp3(
            args.input,
            args.output,
            force=args.force,
        )
        pass

    def tokens(self):
        return self.counttokens()



if __name__ == '__main__':
    rc()
